### ISSUE TITLE
merge branches master and offline-repair into master 

### ISSUE THREAD

**Issue by monperrus** [kth-tcs/sonarqube-repair#14]
in order to have single branch.

delete the other branches from the repo

**Comment by ashutosh1598** [comment]
I tried to merge offline-repair into master, but it was not possible to resolve conflicts. There is a class Bug in my system which has to be significantly different for these branches. So I have added modified sonar-java-checks-testkit to master and added Bug class by  another name BugOffline. So now if master is to be used for doing offline repair, some change would have to be made. Replacing API call by sonar-check  call and replacing Bug by BugOffline.

Also I did `push --all` by mistake so branch sniper has reappeared. You can delete both sniper and offline-repair now.
